version: '3'

services:

  vsql:
    #image: mariadb:10.2
    image: blackflysolutions/mariadb:10.2
    expose:
           - "3306"
    volumes:
      - vdb:/var/lib/mysql
    environment:
      - VSITE_ENVIRONMENT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
   
  vhttp:
    image: blackflysolutions/drupal:8-apache-civicrm-5
    #image: blackflysolutions/prosimulium:8-apache
    #image: prosimulium:8-apache
    deploy:
      labels:
        simuliidae.domain: "{VSITE_DOMAIN}"
    ports:
      - 80/tcp
    volumes:
      - vdrupal:/var/www/drupal
    environment:
      - VSITE
      - VSITE_SITES
      - VSITE_DOMAIN
      - VSITE_ENVIRONMENT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE
    depends_on:
      - vsql

  admin:
    # use an extended version of the above image for administrative tasks
    image: blackflysolutions/simuliidae-admin:8-apache-civicrm-5
    #image: blackflysolutions/prosimulium:8-apache-admin
    #image: prosimulium:8-apache-admin
    volumes:
      - vdrupal:/var/www/drupal
    environment:
      - VSITE
      - VSITE_SITES
      - VSITE_DOMAIN
      - VSITE_ENVIRONMENT
      - VSITE_CIVICRM_VER
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE

    depends_on:
      - vsql
      - vhttp

volumes:
  vdrupal:
  vdb:
