services:
  admin:
    depends_on:
    - vhttp
    - vsql
    deploy:
      labels:
        simuliidae.civicrm.version: '${VSITE_CIVICRM_VER}'
        simuliidae.domain: '${VSITE_DOMAIN}'
        simuliidae.environment: '${VSITE_ENVIRONMENT-Production}'
      placement:
        constraints:
        - node.hostname==${VSITE_NODE-falcoe}
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2000M
      restart_policy:
        condition: none
    environment:
      CIVICRM_DATABASE: null
      DRUPAL_DATABASE: null
      DRUSH_OPTIONS_URI: '${VSITE_DOMAIN}'
      MYSQL_DATABASE: null
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: null
      VSITE: null
      VSITE_CIVICRM_VER: null
      VSITE_CIVIMAIL_SMTP_DEFAULT: null
      VSITE_DOMAIN: null
      VSITE_DRUPAL_VER: null
      VSITE_ENVIRONMENT: null
      VSITE_SITES: null
    image: prosimulium:8-apache-admin
    labels:
      simuliidae.civicrm.version: '${VSITE_CIVICRM_VER}'
      simuliidae.domain: '${VSITE_DOMAIN}'
      simuliidae.environment: '${VSITE_ENVIRONMENT-Production}'
    volumes:
    - /home/drupal/.ssh:/home/drupal/.ssh:ro
    - /home/backup/.ssh:/root/.backup-ssh:ro
    - /${VSITE_ORIGIN_NODE}var/backup/docker/${VSITE}:/var/restore:rw
    - vdrupal:/var/www/drupal:rw
  vhttp:
    depends_on:
    - vsql
    deploy:
      labels:
        simuliidae.civicrm.version: '${VSITE_CIVICRM_VER}'
        simuliidae.domain: '${VSITE_DOMAIN}'
        simuliidae.domainaliases: '${VSITE_DOMAIN_ALIASES}'
        simuliidae.domainalternatives: '${VSITE_DOMAIN_ALTERNATIVES}'
        simuliidae.environment: '${VSITE_ENVIRONMENT-Production}'
      placement:
        constraints:
        - node.hostname==${VSITE_NODE-falcoe}
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '${VSITE_HTTP_MEMORY-500M}'
      restart_policy:
        max_attempts: 2
    environment:
      CIVICRM_DATABASE: null
      DRUPAL_DATABASE: null
      MYSQL_DATABASE: null
      MYSQL_PASSWORD: null
      MYSQL_USER: null
      VSITE: null
      VSITE_CIVIMAIL_SMTP_DEFAULT: null
      VSITE_DOMAIN: null
      VSITE_ENVIRONMENT: null
      VSITE_SITES: null
    image: prosimulium:8-apache
    labels:
      simuliidae.civicrm.version: '${VSITE_CIVICRM_VER}'
      simuliidae.domain: '${VSITE_DOMAIN}'
      simuliidae.environment: '${VSITE_ENVIRONMENT-Production}'
    ports:
    - protocol: tcp
      target: 80
    volumes:
    - vdrupal:/var/www/drupal:rw
  vsql:
    deploy:
      labels:
        simuliidae.civicrm.version: '${VSITE_CIVICRM_VER}'
        simuliidae.domain: '${VSITE_DOMAIN}'
        simuliidae.environment: '${VSITE_ENVIRONMENT-Production}'
      placement:
        constraints:
        - node.hostname==${VSITE_NODE-falcoe}
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '${VSITE_SQL_MEMORY-4000M}'
      restart_policy:
        max_attempts: 2
    environment:
      MYSQL_DATABASE: null
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: null
      VSITE_ENVIRONMENT: null
    expose:
    - '3306'
    image: blackflysolutions/mariadb:10.3
    labels:
      simuliidae.civicrm.version: '${VSITE_CIVICRM_VER}'
      simuliidae.domain: '${VSITE_DOMAIN}'
      simuliidae.environment: '${VSITE_ENVIRONMENT-Production}'
    volumes:
    - vdb:/var/lib/mysql:rw
version: '3.4'
volumes:
  vdb: {}
  vdrupal: {}

