version: '3'

services:

  vhttp:
    image: drupal:7-apache
    build:
      context: drupal
    ports:
      - "1978:80"

  admin:
    image: simuliidae-admin:7-apache
    build:
      context: admin
      args:
        - REPOSITORY_FROM=
