# to use this, we need to define:
#VSITE_SFTP_USER=
#VSITE_SFTP_PASSWORD=b1795c88e4d445f1a33
version: '3.4'
services:
  sftp:
    # enable file management via sftp
    image: "blackflysolutions/sftp:alpine"
    volumes:
      - vsite:/home/${VSITE_SFTP_USER}/${VSITE}
      - /var/www/ssh-keys/host/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key 
      - /var/www/ssh-keys/host/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key 
      - /var/www/ssh-keys/${VSITE_SFTP_USER}/id_rsa.pub:/home/${VSITE_SFTP_USER}/.ssh/keys/id_rsa.pub:ro
    ports:
      - target: 22
        published: "${VSITE_SFTP_PORT}"
        protocol: tcp
        mode: ingress
    command: "${VSITE_SFTP_USER}:${VSITE_SFTP_PASSWORD}:1978"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==${VSITE_NODE-$THIS_NODE}
      resources:
        limits:
          cpus: "1"
          memory: "120M"

volumes:
    vsite:
