version: '3.4'

services:

  vsql:
    image: blackflysolutions/mariadb:{VSITE_MARIADB_VER-10.5}
    expose:
           - "3306"
    volumes:
      - vdb:/var/lib/mysql
    environment:
      - VSITE_ENVIRONMENT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
   
  vhttp:
    image: blackflysolutions/simuliidae-drupal:vhttp-crm-10.3-php8.2-apache-bullseye
    deploy:
      labels:
        simuliidae.domain: "{VSITE_DOMAIN}"
    ports:
      - 80/tcp
    volumes:
      - vsite:/var/www/drupal/web/sites/default
    environment:
      - VSITE
      - VSITE_SITES
      - VSITE_DOMAIN
      - VSITE_DOMAIN_ALTERNATIVES
      - VSITE_ENVIRONMENT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE
    depends_on:
      - vsql

  admin:
    # use an extended version of the above image for administrative tasks
    image: blackflysolutions/simuliidae-drupal:admin-crm-10.3-php8.2-apache-bullseye
    volumes:
      - vsite:/var/www/drupal/web/sites/default
    environment:
      - VSITE
      - VSITE_SITES
      - VSITE_DOMAIN
      - VSITE_DOMAIN_ALTERNATIVES
      - DRUSH_OPTIONS_URI={VSITE_DOMAIN}
      - VSITE_ENVIRONMENT
      - VSITE_CIVICRM_VER
      - VSITE_DRUPAL_VER
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE

    depends_on:
      - vsql
      - vhttp

volumes:
  vdb:
  vsite:
    labels:
      simuliidae.backup.exclude: "{VSITE_BACKUP_EXCLUDE}"
