version: '3.4'

services:

  vsql:
    image: blackflysolutions/mariadb:10.2
    volumes:
      - vdb:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - VSITE_ENVIRONMENT
   
  vhttp:
    image: blackflysolutions/prosimulium:7-apache
    #image: prosimulium:7-apache
    ports:
           - "80/tcp"
    volumes:
      - vsite:/var/www/html/sites/default
    environment:
      - VSITE
      - VSITE_SITE
      - VSITE_ENVIRONMENT
      - VSITE_DOMAIN
      - VSITE_DOMAIN_ALTERNATIVES
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE
    depends_on:
      - vsql

  admin:
    # create a new, empty site at this location
    # build a temporary super-set of the vhttp container above, run some scripts, and then (maybe) exit.
    image: blackflysolutions/prosimulium:7-apache-admin
    #image: prosimulium:7-apache-admin
    #build:
    #  context: admin
    volumes:
      - vsite:/var/www/html/sites/default
    environment:
      - VSITE
      - VSITE_SITES
      - VSITE_ENVIRONMENT
      - VSITE_DOMAIN
      - VSITE_DOMAIN_ALTERNATIVES
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - DRUPAL_DATABASE
      - CIVICRM_DATABASE
      - VSITE_USER_NAME
      - VSITE_USER_MAIL
      - VSITE_USER_ROLE
      - VSITE_FEATURE
      - VSITE_THEME

    depends_on:
      - vsql
      - vhttp

volumes:
    vsite:
    vdb:
